/**
 * Alert composer with live citizen preview (Sections 31, 32).
 *
 * The draft is generated by the backend from the live engine — the browser
 * never writes the risk numbers, the "why", or the recommended actions itself.
 * The officer edits wording, sees exactly what a citizen would see, and only
 * then issues.
 */
import { Eye, Send, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../lib/api'
import { LEVEL_COLOR, fmtPeople, withAlpha } from '../lib/format'
import { useApi, useMutation } from '../lib/hooks'
import type { AlertLevel, Lang } from '../lib/types'
import { Button, Chip, ErrorBlock, LoadingBlock, Spinner } from './ui'

interface Suggested {
  level: AlertLevel
  hazard: string
  hazard_label: string
  title: string
  message: string
  message_hi: string
  what: string
  where: string
  when: string
  why: string
  what_to_do: string
  recommended_actions: string[]
  confidence: number
  geofence: { kind: string; lat: number; lng: number; radius_km: number }
  estimated_exposed_population: number
  covered_location_ids: string[]
}

export function AlertComposer({
  onClose,
  onCreated,
  initialLocationId,
}: {
  onClose: () => void
  onCreated: (id: string) => void
  initialLocationId?: string
}) {
  const locations = useApi(() => api.locations(), { liveUpdate: false })
  const [locationId, setLocationId] = useState(initialLocationId ?? '')
  const [level, setLevel] = useState<AlertLevel | ''>('')
  const [lang, setLang] = useState<Lang>('en')

  const [message, setMessage] = useState('')
  const [messageHi, setMessageHi] = useState('')
  const [actions, setActions] = useState<string[]>([])
  const [radiusKm, setRadiusKm] = useState(6)
  const [expiresIn, setExpiresIn] = useState(6)
  const [issueNow, setIssueNow] = useState(false)
  const [touched, setTouched] = useState(false)

  useEffect(() => {
    if (!locationId && locations.data?.locations?.length) {
      setLocationId(locations.data.locations[0].id)
    }
  }, [locations.data, locationId])

  const preview = useMutation((body: Parameters<typeof api.previewAlert>[0]) => api.previewAlert(body))
  const create = useMutation((body: Record<string, unknown>) => api.createAlert(body))

  const [suggested, setSuggested] = useState<Suggested | null>(null)
  const [engine, setEngine] = useState<Record<string, unknown> | null>(null)
  const [unavailableReason, setUnavailableReason] = useState<string | null>(null)

  const loadPreview = async (force = false) => {
    if (!locationId) return
    setUnavailableReason(null)
    const res = (await preview.run({
      location_id: locationId,
      level: level || undefined,
      language: lang,
    })) as { available?: boolean; reason?: string; suggested?: Suggested; engine?: Record<string, unknown> } | null
    if (!res) return
    if (!res.available) {
      setSuggested(null)
      setUnavailableReason(res.reason ?? 'The engine could not produce a draft for this area.')
      return
    }
    const s = res.suggested!
    setSuggested(s)
    setEngine(res.engine ?? null)
    // `force` overrides the `touched` flag: the "Reset to engine draft" button
    // must restore the fields even though the user has already edited them
    // (a setState above cannot be read from this closure, so force is explicit).
    if (!touched || force) {
      setMessage(s.message)
      setMessageHi(s.message_hi)
      setActions(s.recommended_actions ?? [])
      setRadiusKm(s.geofence?.radius_km ?? 6)
      if (!level) setLevel(s.level)
    }
  }

  useEffect(() => {
    if (locationId) void loadPreview()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [locationId, lang])

  const effectiveLevel = (level || suggested?.level || 'WATCH') as AlertLevel
  const color = LEVEL_COLOR[effectiveLevel]

  const canSubmit = useMemo(
    () => !!locationId && !!suggested && message.trim().length >= 10,
    [locationId, suggested, message],
  )

  const submit = async () => {
    if (!suggested) return
    const created = await create.run({
      location_id: locationId,
      hazard: suggested.hazard,
      level: effectiveLevel,
      title: suggested.title,
      message,
      message_hi: messageHi,
      recommended_actions: actions.filter((a) => a.trim()),
      what: suggested.what,
      when: suggested.when,
      why: suggested.why,
      what_to_do: suggested.what_to_do,
      geofence: { kind: 'radius', radius_km: radiusKm },
      target_audience: ['citizen', 'authority'],
      expires_in_hours: expiresIn,
      issue_immediately: issueNow,
    })
    if (created) onCreated((created as { id: string }).id)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-ink-950/80 p-4 backdrop-blur-sm">
      <div className="panel my-4 w-full max-w-5xl">
        <header className="flex items-center justify-between border-b border-ink-700/60 px-4 py-3">
          <div>
            <h2 className="text-sm font-semibold text-ink-50">Compose alert</h2>
            <p className="text-[11px] text-ink-400">
              Draft generated by the engine · you decide what is issued
            </p>
          </div>
          <Button variant="ghost" size="sm" icon={<X size={15} />} onClick={onClose} title="Close" />
        </header>

        <div className="grid gap-4 p-4 lg:grid-cols-[1fr_22rem]">
          {/* --------------------------------------------------- form --- */}
          <div className="space-y-3">
            <div className="grid gap-2 sm:grid-cols-3">
              <label className="block sm:col-span-2">
                <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                  Area
                </span>
                {locations.data ? (
                  <select
                    value={locationId}
                    onChange={(e) => setLocationId(e.target.value)}
                    className="w-full rounded-md border border-ink-600 bg-ink-850 px-2 py-1.5 text-xs text-ink-100"
                  >
                    {locations.data.locations.map((l) => (
                      <option key={l.id} value={l.id}>
                        {l.name} — {l.district}
                      </option>
                    ))}
                  </select>
                ) : (
                  <LoadingBlock rows={1} />
                )}
              </label>

              <label className="block">
                <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                  Level
                </span>
                <select
                  value={level}
                  onChange={(e) => {
                    setLevel(e.target.value as AlertLevel)
                    setTouched(true)
                  }}
                  className="w-full rounded-md border border-ink-600 bg-ink-850 px-2 py-1.5 text-xs text-ink-100"
                >
                  <option value="">Engine suggestion</option>
                  <option value="WATCH">WATCH</option>
                  <option value="WARNING">WARNING</option>
                  <option value="CRITICAL">CRITICAL</option>
                </select>
              </label>
            </div>

            {preview.pending && (
              <p className="flex items-center gap-1.5 text-[11px] text-ink-400">
                <Spinner size={11} /> Asking the engine for a draft…
              </p>
            )}
            <ErrorBlock error={preview.error} compact />
            {unavailableReason && (
              <div className="rounded-md border border-moderate/40 bg-moderate/10 px-2.5 py-2 text-[11px] text-moderate">
                {unavailableReason}
              </div>
            )}

            {suggested && (
              <>
                {engine && (
                  <div className="flex flex-wrap gap-1.5">
                    <Chip tone="neutral">risk {Number(engine.risk).toFixed(0)}/100</Chip>
                    <Chip tone="neutral">hazard {Number(engine.hazard_score).toFixed(0)}</Chip>
                    <Chip tone="neutral">exposure {Number(engine.exposure_score).toFixed(0)}</Chip>
                    <Chip tone="neutral">confidence {Number(engine.confidence).toFixed(0)}%</Chip>
                    <Chip tone="info">{suggested.hazard_label}</Chip>
                  </div>
                )}

                <label className="block">
                  <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                    Message (English) — {message.length}/2000
                  </span>
                  <textarea
                    value={message}
                    onChange={(e) => {
                      setMessage(e.target.value)
                      setTouched(true)
                    }}
                    rows={4}
                    maxLength={2000}
                    className="w-full rounded-md border border-ink-600 bg-ink-850 px-2.5 py-2 text-xs leading-relaxed text-ink-100"
                  />
                  {message.trim().length < 10 && (
                    <span className="mt-0.5 block text-[10px] text-critical">
                      At least 10 characters are required.
                    </span>
                  )}
                </label>

                <label className="block">
                  <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                    संदेश (Hindi)
                  </span>
                  <textarea
                    value={messageHi}
                    onChange={(e) => {
                      setMessageHi(e.target.value)
                      setTouched(true)
                    }}
                    rows={3}
                    maxLength={2000}
                    className="w-full rounded-md border border-ink-600 bg-ink-850 px-2.5 py-2 text-xs leading-relaxed text-ink-100"
                  />
                </label>

                <div>
                  <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                    Recommended actions
                  </span>
                  <div className="space-y-1">
                    {actions.map((act, i) => (
                      <div key={i} className="flex gap-1.5">
                        <input
                          value={act}
                          onChange={(e) => {
                            const next = [...actions]
                            next[i] = e.target.value
                            setActions(next)
                            setTouched(true)
                          }}
                          className="w-full rounded-md border border-ink-600 bg-ink-850 px-2 py-1 text-[11px] text-ink-100"
                        />
                        <Button
                          size="sm"
                          variant="ghost"
                          icon={<X size={12} />}
                          onClick={() => setActions(actions.filter((_, j) => j !== i))}
                        />
                      </div>
                    ))}
                    {actions.length < 12 && (
                      <Button size="sm" variant="ghost" onClick={() => setActions([...actions, ''])}>
                        + Add action
                      </Button>
                    )}
                  </div>
                </div>

                <div className="grid gap-2 sm:grid-cols-2">
                  <label className="block">
                    <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                      Geofence radius: {radiusKm.toFixed(1)} km
                    </span>
                    <input
                      type="range"
                      min={1}
                      max={25}
                      step={0.5}
                      value={radiusKm}
                      onChange={(e) => setRadiusKm(Number(e.target.value))}
                      className="w-full accent-[var(--color-accent)]"
                    />
                  </label>
                  <label className="block">
                    <span className="mb-1 block text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                      Expires in {expiresIn} h
                    </span>
                    <input
                      type="range"
                      min={1}
                      max={48}
                      step={1}
                      value={expiresIn}
                      onChange={(e) => setExpiresIn(Number(e.target.value))}
                      className="w-full accent-[var(--color-accent)]"
                    />
                  </label>
                </div>

                <label className="flex items-center gap-2 text-[11px] text-ink-300">
                  <input
                    type="checkbox"
                    checked={issueNow}
                    onChange={(e) => setIssueNow(e.target.checked)}
                    className="accent-[var(--color-accent)]"
                  />
                  Issue immediately on creation (otherwise it is saved for review)
                </label>

                <ErrorBlock error={create.error} compact />

                <div className="flex items-center gap-2 border-t border-ink-700/50 pt-3">
                  <Button
                    variant="primary"
                    icon={<Send size={13} />}
                    disabled={!canSubmit}
                    pending={create.pending}
                    onClick={submit}
                  >
                    {issueNow ? 'Create & issue' : 'Create for review'}
                  </Button>
                  <Button variant="ghost" onClick={onClose}>
                    Cancel
                  </Button>
                  <Button size="sm" variant="ghost" onClick={() => { setTouched(false); void loadPreview(true) }}>
                    Reset to engine draft
                  </Button>
                </div>
              </>
            )}
          </div>

          {/* ------------------------------------------------ preview --- */}
          <aside className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="flex items-center gap-1.5 text-[10px] font-semibold tracking-wide text-ink-500 uppercase">
                <Eye size={11} /> Citizen preview
              </span>
              <div className="flex overflow-hidden rounded border border-ink-600">
                {(['en', 'hi'] as Lang[]).map((l) => (
                  <button
                    key={l}
                    type="button"
                    onClick={() => setLang(l)}
                    className={
                      lang === l
                        ? 'bg-accent/25 px-1.5 py-0.5 text-[10px] text-accent-bright'
                        : 'px-1.5 py-0.5 text-[10px] text-ink-400'
                    }
                  >
                    {l === 'en' ? 'EN' : 'हि'}
                  </button>
                ))}
              </div>
            </div>

            <div className="mx-auto w-full max-w-[19rem] rounded-2xl border-4 border-ink-800 bg-ink-950 p-2.5 shadow-2xl">
              <div className="mb-2 flex items-center justify-between px-1 text-[9px] text-ink-600">
                <span>PEHRA</span>
                <span>now</span>
              </div>
              {suggested ? (
                <div
                  className="rounded-xl border p-3"
                  style={{ borderColor: withAlpha(color, 0.5), background: withAlpha(color, 0.1) }}
                >
                  <div
                    className="mb-1.5 inline-block rounded px-1.5 py-0.5 text-[9px] font-bold tracking-wider"
                    style={{ color, background: withAlpha(color, 0.2) }}
                  >
                    {effectiveLevel}
                  </div>
                  <p className="text-[11px] leading-relaxed text-ink-100">
                    {lang === 'hi' && messageHi ? messageHi : message}
                  </p>
                  {actions.filter(Boolean).length > 0 && (
                    <ul className="mt-2 space-y-0.5 border-t border-ink-700/40 pt-2">
                      {actions.filter(Boolean).slice(0, 4).map((act, i) => (
                        <li key={i} className="flex gap-1 text-[10px] text-ink-200">
                          <span style={{ color }}>›</span>
                          {act}
                        </li>
                      ))}
                    </ul>
                  )}
                  <div className="mt-2 flex items-center justify-between border-t border-ink-700/40 pt-1.5 text-[9px] text-ink-500">
                    <span>~{fmtPeople(suggested.estimated_exposed_population)} in zone</span>
                    <span>confidence {suggested.confidence.toFixed(0)}%</span>
                  </div>
                  <button
                    type="button"
                    disabled
                    className="mt-2 w-full rounded-md border border-ink-600 py-1 text-[10px] text-ink-400"
                  >
                    I understand
                  </button>
                </div>
              ) : (
                <div className="rounded-xl border border-dashed border-ink-700 p-4 text-center text-[10px] text-ink-600">
                  Choose an area to generate a draft
                </div>
              )}
            </div>

            <p className="text-[10px] leading-snug text-ink-500">
              This is exactly what a citizen inside the geofence would see. Nothing has been sent —
              delivery only happens after approval, and even then it is simulated.
            </p>
          </aside>
        </div>
      </div>
    </div>
  )
}
