"""Server-Sent Events bus (Section 55).

Real-time transport for risk updates, alert changes, threat movement and
simulation ticks. Events are generated by *this application's* simulation
clock, never presented as live real-world observations -- every payload carries
`is_simulated: true`.
"""
from __future__ import annotations

import asyncio
import datetime as dt
import json
from typing import Any, AsyncIterator, Dict, List, Set


class EventBus:
    def __init__(self, max_queue: int = 64) -> None:
        self._subscribers: Set[asyncio.Queue] = set()
        self._max_queue = max_queue
        self._history: List[dict] = []

    def subscribe(self) -> asyncio.Queue:
        q: asyncio.Queue = asyncio.Queue(maxsize=self._max_queue)
        self._subscribers.add(q)
        return q

    def unsubscribe(self, q: asyncio.Queue) -> None:
        self._subscribers.discard(q)

    def publish(self, event_type: str, data: Dict[str, Any]) -> None:
        payload = {
            "type": event_type,
            "at": dt.datetime.now(dt.timezone.utc).replace(tzinfo=None).isoformat() + "Z",
            "is_simulated": True,
            "data": data,
        }
        self._history.append(payload)
        self._history = self._history[-100:]
        dead = []
        for q in self._subscribers:
            try:
                q.put_nowait(payload)
            except asyncio.QueueFull:
                dead.append(q)
        for q in dead:
            self._subscribers.discard(q)

    @property
    def subscriber_count(self) -> int:
        return len(self._subscribers)

    def recent(self, limit: int = 20) -> List[dict]:
        return self._history[-limit:]


bus = EventBus()


async def event_stream(queue: asyncio.Queue) -> AsyncIterator[str]:
    """Format queue items as SSE frames, with heartbeats so proxies keep the
    connection open and the client can detect a dead link (Section 36)."""
    yield f": PEHRA event stream connected\n\n"
    try:
        while True:
            try:
                payload = await asyncio.wait_for(queue.get(), timeout=15.0)
            except asyncio.TimeoutError:
                yield ": heartbeat\n\n"
                continue
            yield f"event: {payload['type']}\ndata: {json.dumps(payload)}\n\n"
    except asyncio.CancelledError:  # client disconnected
        raise
